# Generated by Django 4.0.4 on 2022-05-18 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('InspectionID', models.IntegerField(default=0)),
                ('PipeID', models.CharField(max_length=6)),
                ('Length', models.IntegerField(default=0)),
                ('Width', models.IntegerField(default=0)),
                ('Rating', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Table2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ConditionID', models.IntegerField(default=0)),
                ('Distance', models.IntegerField(default=0)),
                ('Code', models.CharField(max_length=3)),
                ('InspectionID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InfraTieDemo.table1')),
            ],
        ),
    ]
